// String Mətn

let ad = "Farid";
let mesaj = 'Salam necesen?';
console.log(mesaj);

// Number

let yas = 20;
let pi = 3.14;
console.log(yas)

// Boolean Dəyər, Məntiqi Dəyər

let aktiv = true;
let adminMI = false;
console.log(adminMI)

// Object Əşya

let istifadeci = {
    ad: "Farid",
    soyad: "Allahverdiyev",
    yas: 20,
    admin: true
};
console.log(istifadeci);

// Array Massiv

let sayilar = [10, 20, 30, 40];
console.log(sayilar)

// Null Boş Dəyər

let bosDeyer = null;
console.log(bosDeyer)

// Undefined Müəyyən edilməmiş

let tanimsiz;
console.log(tanimsiz);
console.log(typetanimsiz);

// BigInt Böyük Sayılar

let boyukSayi = 12345678900987654321n;
console.log(typeofboyukSayi);

// Symbol

let id = Symbol("benzersizID");
console.log(typeof id); // symbol

// Key və Value dəyəri


